services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    hostname: stalkers-messages
    networks:
      - stalkers-network

  mysqldb:
    image: mysql:8.0.33
    command:
      - "--skip-performance-schema"
      - "--skip-mysqlx"
      - "--innodb-buffer-pool-size=2G"
      - "--innodb-log-buffer-size=512M"
      - "--innodb-buffer-pool-instances=2"
      - "--join-buffer-size=2M"
    container_name: "mysqldb"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=stalkers
      - MYSQL_ROOT_PASSWORD=${DATASOURCE_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - stalkers-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s

  stalkers-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stalkers-api
    image: stalkers-api:latest
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - LOCAL_IMAGE_DIRECTORY=/app/images
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OAUTH2_GOOGLE_HEADER=${OAUTH2_GOOGLE_HEADER}
      - OAUTH2_GOOGLE_SECRET=${OAUTH2_GOOGLE_SECRET}
      - ROBOT_HEADER=${ROBOT_HEADER}
      - ROBOT_SECRET=${ROBOT_SECRET}
    volumes:
      - api-images:/app/images
    networks:
      - stalkers-network

  redis:
    image: redis:latest
    container_name: "redisdb"
    ports:
      - "6379:6379"
    networks:
      - stalkers-network
    volumes:
      - redis-data:/data

volumes:
  api-images:
  mysql-data:
  redis-data:
    driver: local
networks:
  stalkers-network:
    name: stalkers-network