services:
  stalkers-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stalkers-api
    image: stalkers-api:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - LOCAL_IMAGE_DIRECTORY=/app/images
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OAUTH2_GOOGLE_HEADER=${OAUTH2_GOOGLE_HEADER}
      - OAUTH2_GOOGLE_SECRET=${OAUTH2_GOOGLE_SECRET}
      - ROBOT_HEADER=${ROBOT_HEADER}
      - ROBOT_SECRET=${ROBOT_SECRET}
    volumes:
      - api-images:/app/images
    networks:
      - stalkers-network

volumes:
  api-images:
networks:
  stalkers-network:
    name: stalkers-network