name: Deploy Stalkers
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} > ~/.ssh/known_hosts

      - name: Deploy JAR to Server
        run: |
          REMOTE_SERVER="${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}"
          HOME_DIR="~/../victor2_miralhas"

          ssh $REMOTE_SERVER << EOF
            cd $HOME_DIR
            sudo bash deploy.sh
          EOF